//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal_Projects
    {
        public portal_Projects()
        {
            this.cms_News = new HashSet<cms_News>();
            this.share_Images = new HashSet<share_Images>();
        }
    
        public int Id { get; set; }
        public int Region { get; set; }
        public string Address { get; set; }
        public string Investor { get; set; }
        public string ProjectPackage { get; set; }
        public string TotalInvestment { get; set; }
        public string Duration { get; set; }
        public int ProgressStatus { get; set; }
        public int Type { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CoverImageId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Description2 { get; set; }
    
        public virtual ICollection<cms_News> cms_News { get; set; }
        public virtual ICollection<share_Images> share_Images { get; set; }
        public virtual share_Images CoverImage { get; set; }
    }
}
